# Generated by Django 2.2.6 on 2019-11-11 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='抖音：记录美好生活', max_length=50)),
                ('text', models.TextField(default='App简介')),
                ('url', models.CharField(default='Http://', max_length=100)),
                ('icno', models.ImageField(default='default.png', upload_to='images/')),
                ('image', models.ImageField(default='1.jpg', upload_to='images/')),
                ('votes', models.IntegerField(default=1)),
                ('pub_date', models.DateTimeField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
